// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytpdbvglbhhdaufjuvtt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0cGRidmdsYmhoZGF1Zmp1dnR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3ODg1NDIsImV4cCI6MjA3MDM2NDU0Mn0.HTsQxEHTWu8mEXvziVoLi1qoV95VsNi9xrNVM_xvjWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});